version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myserver
      POSTGRES_DB: stream-stream
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  rabbitmq:
    image: rabbitmq:3-management
volumes:
  postgres_data:
