
#### SEND REQUEST TO GETS SONGS
GET http://localhost:8080/profile


#### FIND A SONG
GET http://localhost:8080/users/1

#### CREATE A NEW SONG
POST http://localhost:8080/playlists
Content-Type: application/json

{
    "name": "Feel Good Now",
    "songs": [6],
    "user": 2
}

#### UPDATE A SONG
PUT http://localhost:8080/songs/5
Content-Type: application/json

{
    "title": "Kese",
    "artists": ["wizzkid"],
    "releasedDate": "2024-12-01",
    "duration": "02:45",
    "lyrics": "kese kese kese"
}

#### REMOVE A SONG
DELETE http://localhost:8080/songs/6
