
#### SEND REQUEST TO GETS A PROFILE
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdEBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTczNTM4NzQ4MSwiZXhwIjoxNzM1NDczODgxfQ.6SlVtKAGykfS-zTqfYsOh2MdoV5wzalaNHbBNx1p38c

#### LOGIN A USER
POST  http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "mary@gmail.com",
    "password": "123456"
}

#### CREATE A NEW User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "mary",
    "lastName": "alegun",
    "email": "mary@gmail.com",
    "password": "123456"
}


