
#### SEND REQUEST TO GETS A PROFILE
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdEBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTczNTM4NzQ4MSwiZXhwIjoxNzM1NDczODgxfQ.6SlVtKAGykfS-zTqfYsOh2MdoV5wzalaNHbBNx1p38c

#### LOGIN A USER
POST  http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "ayomidesherif2019@gmail.com",
  "password": "Testing26377#!@"
}

#### CREATE A NEW User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "Amodu monica",
  "email": "ayomidesherif2019@gmail.com",
  "phone": "+243903789393",
  "subscription": "free",
  "password": "Test123#@",
  "terms_of_service": true
}

#### CREATE A NEW User
DELETE  http://localhost:9200/songs
Content-Type: application/json


#### SEND REQUEST TO FORGOT PASSWORD
POST http://localhost:8080/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "ayomidesherif2019@gmail.com"
}


#### SEND REQUEST TO RESEND VERIFICATION EMAIL CODE
GET http://localhost:8080/api/v1/auth/resend-email-code
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5b21pZGVzaGVyaWYyMDE5QGdtYWlsLmNvbSIsImlhdCI6MTc0MjY4NTAxNCwiZXhwIjoxNzQyOTQ0MjE0fQ.JqTjd-y6mJXexJT7RuC1xgAU-9ZY5hYVqqkaXeiPyUI


#### SEND REQUEST TO VERIFY FORGOT PASSWORD CODE
POST  http://localhost:8080/api/v1/auth/forgot-password-code
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5b21pZGVzaGVyaWYyMDE5QGdtYWlsLmNvbSIsImlhdCI6MTc0MjY4NTAxNCwiZXhwIjoxNzQyOTQ0MjE0fQ.JqTjd-y6mJXexJT7RuC1xgAU-9ZY5hYVqqkaXeiPyUI

{
  "verificationCode": "332161"
}

#### SEND REQUEST TO RESET PASSWORD
PATCH http://localhost:8080/api/v1/auth/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5b21pZGVzaGVyaWYyMDE5QGdtYWlsLmNvbSIsImlhdCI6MTc0MjY4NTAxNCwiZXhwIjoxNzQyOTQ0MjE0fQ.JqTjd-y6mJXexJT7RuC1xgAU-9ZY5hYVqqkaXeiPyUI

{
  "new_password": "Testing26377#!@",
  "confirm_newpassword": "Testing26377#!@"
}