export enum NotificationType {
  NEW_MUSIC = 'NEW_MUSIC',
  PLAYLIST_UPDATE = 'PLAYLIST_UPDATE',
  FRIEND_ACTIVITY = 'FRIEND_ACTIVITY',
  SUBSCRIPTION = 'SUBSCRIPTION',
  LISTENING_ACTIVITY = 'LISTENING_ACTIVITY',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',
}
